apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
  labels:
    app: user-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      containers:
      - name: user-seervice-app
        image: {{ .Values.image.repo }}/spring:userservice
        imagePullPolicy: Always
        ports:
        - containerPort: 9002




  