apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka
  
---------------------

apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app:  eureka
  ports:
  - port: 8761
    name: eureka 
  ClusterIP: None 


------------------------

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: priyabratswainn009/spring:service
        ports:
        - containerPort: 8761
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapRef:
                name: eureka-cm
                key: eureka_service_address  

-----------------------------------
apiVersion: v1
kind: Service
metadata:
  name: eurekalb
spec:
  selector:
    app:  eureka
  ports:
  - port: 80
    targetPort: 8761
    name: eureka 
  type: NodePort  












  
