apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service-app
  labels:
    app: department-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service-app
  template:
    metadata:
      labels:
        app: department-service-app
    spec:
      containers:
      - name: deployment-seervice-app
        image: priyabratswainn009/spring:department
        imagePullPolicy: Always
        ports:
        - containerPort: 9001

---------------------------------   

apiVersion: v1
kind: Service
metadata:
  name: department-service-app
spec:
  selector:
    app:  department-service-app
  ports:
  - port: 80
    targetPort: 9001
  type: ClusterIP


  
