apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
      - name: cloud-config-server-app
        image: priyabratswainn009/spring:configserver
        imagePullPolicy: Always
        ports:
        - containerPort: 9296



  
